/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinal;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author pepeu
 */
public class FrameCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FrameCadastro
     */
    public FrameCadastro() {
        initComponents();
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrar = new javax.swing.JButton();
        jLabel1Email = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel1Nome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1CPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JTextField();
        jTextFieldSenhaConfirm = new javax.swing.JTextField();
        jLabelSenhaConfirm = new javax.swing.JLabel();
        jButtonRetornoLogin1 = new javax.swing.JButton();
        jLabelSenhaInfo = new javax.swing.JLabel();
        jLabelSenhaInfo1 = new javax.swing.JLabel();
        jLabelSenhaInfo2 = new javax.swing.JLabel();
        jLabelSenhaInfo3 = new javax.swing.JLabel();
        jLabelSenhaInfo4 = new javax.swing.JLabel();
        jLabelSenhaInvalida = new javax.swing.JLabel();
        jLabel1SenhaIncorreta = new javax.swing.JLabel();
        jLabelCPFIncorreto = new javax.swing.JLabel();
        jLabelEmailIncorreto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabel1Email.setText("Email:");

        jTextFieldEmail.setToolTipText("example@email.com");
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel1Nome.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel1CPF.setText("CPF:");

        jTextFieldCPF.setToolTipText("000.000.000-00");

        jLabelSenha.setText("Senha:");

        jTextFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaActionPerformed(evt);
            }
        });

        jLabelSenhaConfirm.setText("Repita a senha:");

        jButtonRetornoLogin1.setText("Retornar a tela de Login");
        jButtonRetornoLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornoLogin1ActionPerformed(evt);
            }
        });

        jLabelSenhaInfo.setText("A senha deve ter no mínimo:");

        jLabelSenhaInfo1.setText("8 caracteres");

        jLabelSenhaInfo2.setText("1 letra maiúscula");

        jLabelSenhaInfo3.setText("1 letra minúscula");

        jLabelSenhaInfo4.setText("1 número");

        jLabelSenhaInvalida.setForeground(new java.awt.Color(255, 51, 102));
        jLabelSenhaInvalida.setText("jLabel1");

        jLabel1SenhaIncorreta.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1SenhaIncorreta.setText("jLabel1");

        jLabelCPFIncorreto.setForeground(new java.awt.Color(255, 51, 102));
        jLabelCPFIncorreto.setText("jLabel1");

        jLabelEmailIncorreto.setForeground(new java.awt.Color(255, 51, 102));
        jLabelEmailIncorreto.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRetornoLogin1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCadastrar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelSenhaConfirm)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSenhaConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelSenha)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSenha))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1Nome)
                                            .addComponent(jLabel1CPF))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(jTextFieldNome)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEmailIncorreto)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1Email)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldEmail)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPFIncorreto)
                            .addComponent(jLabel1SenhaIncorreta))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSenhaInvalida)
                            .addComponent(jLabelSenhaInfo)
                            .addComponent(jLabelSenhaInfo2)
                            .addComponent(jLabelSenhaInfo1)
                            .addComponent(jLabelSenhaInfo3)
                            .addComponent(jLabelSenhaInfo4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Email)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmailIncorreto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Nome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1CPF)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCPFIncorreto)
                .addGap(18, 18, 18)
                .addComponent(jLabelSenhaInfo)
                .addGap(5, 5, 5)
                .addComponent(jLabelSenhaInfo1)
                .addGap(5, 5, 5)
                .addComponent(jLabelSenhaInfo2)
                .addGap(5, 5, 5)
                .addComponent(jLabelSenhaInfo3)
                .addGap(5, 5, 5)
                .addComponent(jLabelSenhaInfo4)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha)
                    .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabelSenhaInvalida)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenhaConfirm)
                    .addComponent(jTextFieldSenhaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel1SenhaIncorreta)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetornoLogin1)
                    .addComponent(jButtonCadastrar))
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1Email, jTextFieldEmail});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1CPF, jTextFieldCPF});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1Nome, jTextFieldNome});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        this.dispose();
        FrameLogin n = new FrameLogin();
        n.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonRetornoLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornoLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRetornoLogin1ActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonRetornoLogin1;
    private javax.swing.JLabel jLabel1CPF;
    private javax.swing.JLabel jLabel1Email;
    private javax.swing.JLabel jLabel1Nome;
    private javax.swing.JLabel jLabel1SenhaIncorreta;
    private javax.swing.JLabel jLabelCPFIncorreto;
    private javax.swing.JLabel jLabelEmailIncorreto;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSenhaConfirm;
    private javax.swing.JLabel jLabelSenhaInfo;
    private javax.swing.JLabel jLabelSenhaInfo1;
    private javax.swing.JLabel jLabelSenhaInfo2;
    private javax.swing.JLabel jLabelSenhaInfo3;
    private javax.swing.JLabel jLabelSenhaInfo4;
    private javax.swing.JLabel jLabelSenhaInvalida;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JTextField jTextFieldSenhaConfirm;
    // End of variables declaration//GEN-END:variables

    
}
